#if !canImport(ObjectiveC)
import XCTest

extension URLFileManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLFileManagerTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(URLFileManagerTests.__allTests__URLFileManagerTests),
    ]
}
#endif
